Feature/verify access
SmarterApp/TDS_SessionService pull request #13
Opened 2016-10-22 23:03 UTC by jeffjohnson9046

Adds `isInSimulationEnvironment()` and `isInDevelopmentEnvironment()` methods to identify if the environment is configured for "Development" or "SIMULATION".

2016-10-23 19:10 UTC, millerts requested changes

2016-10-23 19:10 UTC, millerts commented on client/src/main/java/tds/session/ExternalSessionConfiguration.java
> +        return this.getEnvironment().equalsIgnoreCase(SIMULATION_ENVIRONMENT);
I believe this will throw if `environment` is null so add a null check?  Here and below.

2016-10-24 06:20 UTC, jtreuting commented on client/src/main/java/tds/session/ExternalSessionConfiguration.java
> +        return this.getEnvironment().equalsIgnoreCase(SIMULATION_ENVIRONMENT);
Base don that, I think you should add a unit test for a NULL environment as well.

2016-10-24 14:54 UTC, jeffjohnson9046 commented on client/src/main/java/tds/session/ExternalSessionConfiguration.java
> +        return this.getEnvironment().equalsIgnoreCase(SIMULATION_ENVIRONMENT);
The `environment` cannot be `null` in either the `session._externs` or the `configs.client_externs` table, so the only way I can see `environment` getting set to `null` is when someone calls `ExternalSessionConfiguration` constructor.  Having said that: a `null` check here is a good safeguard, so I'll add it and a unit test to make sure it works.

2016-10-24 15:00 UTC, millerts commented
Another option if it can never be null is to throw an `IllegalArgumentException` if the constructor is called with null.

2016-10-24 18:15 UTC, merged